//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

public class comwhtwndtypes_BlogComment: Codable {
    public let type = "com.whtwnd.blog.comment"
    public var content: String
    public var entryUri: String

    public init(content: String, entryUri: String) {
        self.content = content
        self.entryUri = entryUri
    }

    enum CodingKeys: String, CodingKey {
        case type = "$type"
        case content
        case entryUri
    }
}
