//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comwhtwndtypes {
    public class BlogNotifyOfNewEntry_Input: Codable {
        public var entryUri: String

        public init(entryUri: String) {
            self.entryUri = entryUri
        }

        enum CodingKeys: String, CodingKey {
            case entryUri
        }
    }

    public class BlogNotifyOfNewEntry_Output: Codable {
        public let type = "com.whtwnd.blog.notifyOfNewEntry"

        public init() {
        }

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }
    }

    public enum BlogNotifyOfNewEntry_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func BlogNotifyOfNewEntry(client: any XRPCClientProtocol, input: BlogNotifyOfNewEntry_Input) async throws -> BlogNotifyOfNewEntry_Output {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "com.whtwnd.blog.notifyOfNewEntry", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw BlogNotifyOfNewEntry_Error(error: error)
        }
    }
}
