//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comwhtwndtypes {
    public class BlogGetAuthorPosts_Output: Codable {
        public var post: [BlogDefs_BlogEntry]

        public init(post: [BlogDefs_BlogEntry]) {
            self.post = post
        }

        enum CodingKeys: String, CodingKey {
            case post
        }
    }

    public enum BlogGetAuthorPosts_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func BlogGetAuthorPosts(client: any XRPCClientProtocol, author: String) async throws -> BlogGetAuthorPosts_Output {
        let params: Parameters = ["author": .string(author)]
        do {
            return try await client.fetch(endpoint: "com.whtwnd.blog.getAuthorPosts", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw BlogGetAuthorPosts_Error(error: error)
        }
    }
}
