//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comwhtwndtypes {
    public class BlogGetMentionsByEntry_Output: Codable {
        public var mentions: [String]

        public init(mentions: [String]) {
            self.mentions = mentions
        }

        enum CodingKeys: String, CodingKey {
            case mentions
        }
    }

    public enum BlogGetMentionsByEntry_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func BlogGetMentionsByEntry(client: any XRPCClientProtocol, postUri: String) async throws -> BlogGetMentionsByEntry_Output {
        let params: Parameters = ["postUri": .string(postUri)]
        do {
            return try await client.fetch(endpoint: "com.whtwnd.blog.getMentionsByEntry", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw BlogGetMentionsByEntry_Error(error: error)
        }
    }
}
