//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class TempCheckSignupQueue_Output: Codable {
        public var activated: Bool
        public var estimatedTimeMs: Int?
        public var placeInQueue: Int?

        public init(activated: Bool, estimatedTimeMs: Int?, placeInQueue: Int?) {
            self.activated = activated
            self.estimatedTimeMs = estimatedTimeMs
            self.placeInQueue = placeInQueue
        }

        enum CodingKeys: String, CodingKey {
            case activated
            case estimatedTimeMs
            case placeInQueue
        }
    }

    public enum TempCheckSignupQueue_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func TempCheckSignupQueue(client: any XRPCClientProtocol) async throws -> TempCheckSignupQueue_Output {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "com.atproto.temp.checkSignupQueue", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw TempCheckSignupQueue_Error(error: error)
        }
    }
}
