//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class RepoListMissingBlobs_Output: Codable {
        public var blobs: [RepoListMissingBlobs_RecordBlob]
        public var cursor: String?

        public init(blobs: [RepoListMissingBlobs_RecordBlob], cursor: String?) {
            self.blobs = blobs
            self.cursor = cursor
        }

        enum CodingKeys: String, CodingKey {
            case blobs
            case cursor
        }
    }

    public class RepoListMissingBlobs_RecordBlob: Codable {
        public var cid: String
        public var recordUri: String

        public init(cid: String, recordUri: String) {
            self.cid = cid
            self.recordUri = recordUri
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case recordUri
        }
    }

    public enum RepoListMissingBlobs_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func RepoListMissingBlobs(client: any XRPCClientProtocol, cursor: String?, limit: Int?) async throws -> RepoListMissingBlobs_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit)]
        do {
            return try await client.fetch(endpoint: "com.atproto.repo.listMissingBlobs", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw RepoListMissingBlobs_Error(error: error)
        }
    }
}
