//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class IdentityGetRecommendedDidCredentials_Output: Codable {
        public var alsoKnownAs: [String]?
        public var rotationKeys: [String]?
        public var services: LexiconTypeDecoder?
        public var verificationMethods: LexiconTypeDecoder?

        public init(alsoKnownAs: [String]?, rotationKeys: [String]?, services: LexiconTypeDecoder?, verificationMethods: LexiconTypeDecoder?) {
            self.alsoKnownAs = alsoKnownAs
            self.rotationKeys = rotationKeys
            self.services = services
            self.verificationMethods = verificationMethods
        }

        enum CodingKeys: String, CodingKey {
            case alsoKnownAs
            case rotationKeys
            case services
            case verificationMethods
        }
    }

    public enum IdentityGetRecommendedDidCredentials_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func IdentityGetRecommendedDidCredentials(client: any XRPCClientProtocol) async throws -> IdentityGetRecommendedDidCredentials_Output {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "com.atproto.identity.getRecommendedDidCredentials", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw IdentityGetRecommendedDidCredentials_Error(error: error)
        }
    }
}
