//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class AdminUpdateAccountEmail_Input: Codable {
        public var account: String
        public var email: String

        public init(account: String, email: String) {
            self.account = account
            self.email = email
        }

        enum CodingKeys: String, CodingKey {
            case account
            case email
        }
    }

    public enum AdminUpdateAccountEmail_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func AdminUpdateAccountEmail(client: any XRPCClientProtocol, input: AdminUpdateAccountEmail_Input) async throws -> Bool {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "com.atproto.admin.updateAccountEmail", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw AdminUpdateAccountEmail_Error(error: error)
        }
    }
}
