//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class SyncGetRepoStatus_Output: Codable {
        public var active: Bool
        public var did: String
        public var rev: String?
        public var status: String?

        public init(active: Bool, did: String, rev: String?, status: String?) {
            self.active = active
            self.did = did
            self.rev = rev
            self.status = status
        }

        enum CodingKeys: String, CodingKey {
            case active
            case did
            case rev
            case status
        }
    }

    public enum SyncGetRepoStatus_Output_Status: RawRepresentable, Codable {
        public typealias RawValue = String

        case takendown
        case suspended
        case deactivated
        case unknown(String)

        public init?(rawValue: String) {
            switch rawValue {
            case "takendown":
                self = .takendown
            case "suspended":
                self = .suspended
            case "deactivated":
                self = .deactivated
            default:
                self = .unknown(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .takendown:
                "takendown"
            case .suspended:
                "suspended"
            case .deactivated:
                "deactivated"
            case let .unknown(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self (rawValue: rawValue)!
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public enum SyncGetRepoStatus_Error: XRPCError {
        case reponotfound(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "RepoNotFound":
                self = .reponotfound(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .reponotfound:
                return "RepoNotFound"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .reponotfound(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func SyncGetRepoStatus(client: any XRPCClientProtocol, did: String) async throws -> SyncGetRepoStatus_Output {
        let params: Parameters = ["did": .string(did)]
        do {
            return try await client.fetch(endpoint: "com.atproto.sync.getRepoStatus", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw SyncGetRepoStatus_Error(error: error)
        }
    }
}
