//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class ServerRefreshSession_Output: Codable {
        public var accessJwt: String
        public var active: Bool?
        public var did: String
        public var didDoc: LexiconTypeDecoder?
        public var handle: String
        public var refreshJwt: String
        public var status: String?

        public init(accessJwt: String, active: Bool?, did: String, didDoc: LexiconTypeDecoder?, handle: String, refreshJwt: String, status: String?) {
            self.accessJwt = accessJwt
            self.active = active
            self.did = did
            self.didDoc = didDoc
            self.handle = handle
            self.refreshJwt = refreshJwt
            self.status = status
        }

        enum CodingKeys: String, CodingKey {
            case accessJwt
            case active
            case did
            case didDoc
            case handle
            case refreshJwt
            case status
        }
    }

    public enum ServerRefreshSession_Output_Status: RawRepresentable, Codable {
        public typealias RawValue = String

        case takendown
        case suspended
        case deactivated
        case unknown(String)

        public init?(rawValue: String) {
            switch rawValue {
            case "takendown":
                self = .takendown
            case "suspended":
                self = .suspended
            case "deactivated":
                self = .deactivated
            default:
                self = .unknown(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .takendown:
                "takendown"
            case .suspended:
                "suspended"
            case .deactivated:
                "deactivated"
            case let .unknown(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self (rawValue: rawValue)!
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public enum ServerRefreshSession_Error: XRPCError {
        case accounttakedown(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "AccountTakedown":
                self = .accounttakedown(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .accounttakedown:
                return "AccountTakedown"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .accounttakedown(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func ServerRefreshSession(client: any XRPCClientProtocol) async throws -> ServerRefreshSession_Output {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "com.atproto.server.refreshSession", contentType: "*/*", httpMethod: .post, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw ServerRefreshSession_Error(error: error)
        }
    }
}
