//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class ServerGetSession_Output: Codable {
        public var active: Bool?
        public var did: String
        public var didDoc: LexiconTypeDecoder?
        public var email: String?
        public var emailAuthFactor: Bool?
        public var emailConfirmed: Bool?
        public var handle: String
        public var status: String?

        public init(active: Bool?, did: String, didDoc: LexiconTypeDecoder?, email: String?, emailAuthFactor: Bool?, emailConfirmed: Bool?, handle: String, status: String?) {
            self.active = active
            self.did = did
            self.didDoc = didDoc
            self.email = email
            self.emailAuthFactor = emailAuthFactor
            self.emailConfirmed = emailConfirmed
            self.handle = handle
            self.status = status
        }

        enum CodingKeys: String, CodingKey {
            case active
            case did
            case didDoc
            case email
            case emailAuthFactor
            case emailConfirmed
            case handle
            case status
        }
    }

    public enum ServerGetSession_Output_Status: RawRepresentable, Codable {
        public typealias RawValue = String

        case takendown
        case suspended
        case deactivated
        case unknown(String)

        public init?(rawValue: String) {
            switch rawValue {
            case "takendown":
                self = .takendown
            case "suspended":
                self = .suspended
            case "deactivated":
                self = .deactivated
            default:
                self = .unknown(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .takendown:
                "takendown"
            case .suspended:
                "suspended"
            case .deactivated:
                "deactivated"
            case let .unknown(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self (rawValue: rawValue)!
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public enum ServerGetSession_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func ServerGetSession(client: any XRPCClientProtocol) async throws -> ServerGetSession_Output {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "com.atproto.server.getSession", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw ServerGetSession_Error(error: error)
        }
    }
}
