//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class ServerReserveSigningKey_Input: Codable {
        public var did: String?

        public init(did: String?) {
            self.did = did
        }

        enum CodingKeys: String, CodingKey {
            case did
        }
    }

    public class ServerReserveSigningKey_Output: Codable {
        public var signingKey: String

        public init(signingKey: String) {
            self.signingKey = signingKey
        }

        enum CodingKeys: String, CodingKey {
            case signingKey
        }
    }

    public enum ServerReserveSigningKey_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func ServerReserveSigningKey(client: any XRPCClientProtocol, input: ServerReserveSigningKey_Input) async throws -> ServerReserveSigningKey_Output {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "com.atproto.server.reserveSigningKey", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw ServerReserveSigningKey_Error(error: error)
        }
    }
}
