//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class AdminDisableInviteCodes_Input: Codable {
        public var accounts: [String]?
        public var codes: [String]?

        public init(accounts: [String]?, codes: [String]?) {
            self.accounts = accounts
            self.codes = codes
        }

        enum CodingKeys: String, CodingKey {
            case accounts
            case codes
        }
    }

    public enum AdminDisableInviteCodes_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func AdminDisableInviteCodes(client: any XRPCClientProtocol, input: AdminDisableInviteCodes_Input) async throws -> Bool {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "com.atproto.admin.disableInviteCodes", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw AdminDisableInviteCodes_Error(error: error)
        }
    }
}
