//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class RepoDeleteRecord_Input: Codable {
        public var collection: String
        public var repo: String
        public var rkey: String
        public var swapCommit: String?
        public var swapRecord: String?

        public init(collection: String, repo: String, rkey: String, swapCommit: String?, swapRecord: String?) {
            self.collection = collection
            self.repo = repo
            self.rkey = rkey
            self.swapCommit = swapCommit
            self.swapRecord = swapRecord
        }

        enum CodingKeys: String, CodingKey {
            case collection
            case repo
            case rkey
            case swapCommit
            case swapRecord
        }
    }

    public enum RepoDeleteRecord_Error: XRPCError {
        case invalidswap(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "InvalidSwap":
                self = .invalidswap(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .invalidswap:
                return "InvalidSwap"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .invalidswap(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func RepoDeleteRecord(client: any XRPCClientProtocol, input: RepoDeleteRecord_Input) async throws -> Bool {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "com.atproto.repo.deleteRecord", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw RepoDeleteRecord_Error(error: error)
        }
    }
}
