//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class IdentityResolveHandle_Output: Codable {
        public var did: String

        public init(did: String) {
            self.did = did
        }

        enum CodingKeys: String, CodingKey {
            case did
        }
    }

    public enum IdentityResolveHandle_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func IdentityResolveHandle(client: any XRPCClientProtocol, handle: String) async throws -> IdentityResolveHandle_Output {
        let params: Parameters = ["handle": .string(handle)]
        do {
            return try await client.fetch(endpoint: "com.atproto.identity.resolveHandle", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw IdentityResolveHandle_Error(error: error)
        }
    }
}
