//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class ServerDefs_InviteCode: Codable {
        public var available: Int
        public var code: String
        public var createdAt: String
        public var createdBy: String
        public var disabled: Bool
        public var forAccount: String
        public var uses: [ServerDefs_InviteCodeUse]

        public init(available: Int, code: String, createdAt: String, createdBy: String, disabled: Bool, forAccount: String, uses: [ServerDefs_InviteCodeUse]) {
            self.available = available
            self.code = code
            self.createdAt = createdAt
            self.createdBy = createdBy
            self.disabled = disabled
            self.forAccount = forAccount
            self.uses = uses
        }

        enum CodingKeys: String, CodingKey {
            case available
            case code
            case createdAt
            case createdBy
            case disabled
            case forAccount
            case uses
        }
    }

    public class ServerDefs_InviteCodeUse: Codable {
        public var usedAt: String
        public var usedBy: String

        public init(usedAt: String, usedBy: String) {
            self.usedAt = usedAt
            self.usedBy = usedBy
        }

        enum CodingKeys: String, CodingKey {
            case usedAt
            case usedBy
        }
    }
}
