//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class SyncNotifyOfUpdate_Input: Codable {
        public var hostname: String

        public init(hostname: String) {
            self.hostname = hostname
        }

        enum CodingKeys: String, CodingKey {
            case hostname
        }
    }

    public enum SyncNotifyOfUpdate_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func SyncNotifyOfUpdate(client: any XRPCClientProtocol, input: SyncNotifyOfUpdate_Input) async throws -> Bool {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "com.atproto.sync.notifyOfUpdate", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw SyncNotifyOfUpdate_Error(error: error)
        }
    }
}
