//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class RepoListRecords_Output: Codable {
        public var cursor: String?
        public var records: [RepoListRecords_Record]

        public init(cursor: String?, records: [RepoListRecords_Record]) {
            self.cursor = cursor
            self.records = records
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case records
        }
    }

    public class RepoListRecords_Record: Codable {
        public var cid: String
        public var uri: String
        public var value: LexiconTypeDecoder

        public init(cid: String, uri: String, value: LexiconTypeDecoder) {
            self.cid = cid
            self.uri = uri
            self.value = value
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case uri
            case value
        }
    }

    public enum RepoListRecords_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func RepoListRecords(client: any XRPCClientProtocol, collection: String, cursor: String?, limit: Int?, repo: String, reverse: Bool?, rkeyEnd: String?, rkeyStart: String?) async throws -> RepoListRecords_Output {
        let params: Parameters = ["collection": .string(collection), "cursor": .string(cursor), "limit": .integer(limit), "repo": .string(repo), "reverse": .bool(reverse), "rkeyEnd": .string(rkeyEnd), "rkeyStart": .string(rkeyStart)]
        do {
            return try await client.fetch(endpoint: "com.atproto.repo.listRecords", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw RepoListRecords_Error(error: error)
        }
    }
}
