//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class AdminGetAccountInfos_Output: Codable {
        public var infos: [AdminDefs_AccountView]

        public init(infos: [AdminDefs_AccountView]) {
            self.infos = infos
        }

        enum CodingKeys: String, CodingKey {
            case infos
        }
    }

    public enum AdminGetAccountInfos_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func AdminGetAccountInfos(client: any XRPCClientProtocol, dids: [String]) async throws -> AdminGetAccountInfos_Output {
        let params: Parameters = ["dids": .array(dids)]
        do {
            return try await client.fetch(endpoint: "com.atproto.admin.getAccountInfos", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw AdminGetAccountInfos_Error(error: error)
        }
    }
}
