//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class IdentitySubmitPlcOperation_Input: Codable {
        public var operation: LexiconTypeDecoder

        public init(operation: LexiconTypeDecoder) {
            self.operation = operation
        }

        enum CodingKeys: String, CodingKey {
            case operation
        }
    }

    public enum IdentitySubmitPlcOperation_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func IdentitySubmitPlcOperation(client: any XRPCClientProtocol, input: IdentitySubmitPlcOperation_Input) async throws -> Bool {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "com.atproto.identity.submitPlcOperation", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw IdentitySubmitPlcOperation_Error(error: error)
        }
    }
}
