//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class IdentityUpdateHandle_Input: Codable {
        public var handle: String

        public init(handle: String) {
            self.handle = handle
        }

        enum CodingKeys: String, CodingKey {
            case handle
        }
    }

    public enum IdentityUpdateHandle_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func IdentityUpdateHandle(client: any XRPCClientProtocol, input: IdentityUpdateHandle_Input) async throws -> Bool {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "com.atproto.identity.updateHandle", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw IdentityUpdateHandle_Error(error: error)
        }
    }
}
