//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class AdminSearchAccounts_Output: Codable {
        public var accounts: [AdminDefs_AccountView]
        public var cursor: String?

        public init(accounts: [AdminDefs_AccountView], cursor: String?) {
            self.accounts = accounts
            self.cursor = cursor
        }

        enum CodingKeys: String, CodingKey {
            case accounts
            case cursor
        }
    }

    public enum AdminSearchAccounts_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func AdminSearchAccounts(client: any XRPCClientProtocol, cursor: String?, email: String?, limit: Int?) async throws -> AdminSearchAccounts_Output {
        let params: Parameters = ["cursor": .string(cursor), "email": .string(email), "limit": .integer(limit)]
        do {
            return try await client.fetch(endpoint: "com.atproto.admin.searchAccounts", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw AdminSearchAccounts_Error(error: error)
        }
    }
}
