//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class ServerCreateSession_Input: Codable {
        public var authFactorToken: String?
        public var identifier: String
        public var password: String

        public init(authFactorToken: String?, identifier: String, password: String) {
            self.authFactorToken = authFactorToken
            self.identifier = identifier
            self.password = password
        }

        enum CodingKeys: String, CodingKey {
            case authFactorToken
            case identifier
            case password
        }
    }

    public class ServerCreateSession_Output: Codable {
        public var accessJwt: String
        public var active: Bool?
        public var did: String
        public var didDoc: LexiconTypeDecoder?
        public var email: String?
        public var emailAuthFactor: Bool?
        public var emailConfirmed: Bool?
        public var handle: String
        public var refreshJwt: String
        public var status: String?

        public init(accessJwt: String, active: Bool?, did: String, didDoc: LexiconTypeDecoder?, email: String?, emailAuthFactor: Bool?, emailConfirmed: Bool?, handle: String, refreshJwt: String, status: String?) {
            self.accessJwt = accessJwt
            self.active = active
            self.did = did
            self.didDoc = didDoc
            self.email = email
            self.emailAuthFactor = emailAuthFactor
            self.emailConfirmed = emailConfirmed
            self.handle = handle
            self.refreshJwt = refreshJwt
            self.status = status
        }

        enum CodingKeys: String, CodingKey {
            case accessJwt
            case active
            case did
            case didDoc
            case email
            case emailAuthFactor
            case emailConfirmed
            case handle
            case refreshJwt
            case status
        }
    }

    public enum ServerCreateSession_Output_Status: RawRepresentable, Codable {
        public typealias RawValue = String

        case takendown
        case suspended
        case deactivated
        case unknown(String)

        public init?(rawValue: String) {
            switch rawValue {
            case "takendown":
                self = .takendown
            case "suspended":
                self = .suspended
            case "deactivated":
                self = .deactivated
            default:
                self = .unknown(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .takendown:
                "takendown"
            case .suspended:
                "suspended"
            case .deactivated:
                "deactivated"
            case let .unknown(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self (rawValue: rawValue)!
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public enum ServerCreateSession_Error: XRPCError {
        case accounttakedown(String?)
        case authfactortokenrequired(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "AccountTakedown":
                self = .accounttakedown(error.message)
            case "AuthFactorTokenRequired":
                self = .authfactortokenrequired(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .accounttakedown:
                return "AccountTakedown"
            case .authfactortokenrequired:
                return "AuthFactorTokenRequired"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .accounttakedown(message):
                return message
            case let .authfactortokenrequired(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func ServerCreateSession(client: any XRPCClientProtocol, input: ServerCreateSession_Input) async throws -> ServerCreateSession_Output {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "com.atproto.server.createSession", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw ServerCreateSession_Error(error: error)
        }
    }
}
