//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class RepoStrongRef: Codable {
        public var cid: String
        public var uri: String

        public init(cid: String, uri: String) {
            self.cid = cid
            self.uri = uri
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case uri
        }
    }
}
