//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class ServerCreateInviteCode_Input: Codable {
        public var forAccount: String?
        public var useCount: Int

        public init(forAccount: String?, useCount: Int) {
            self.forAccount = forAccount
            self.useCount = useCount
        }

        enum CodingKeys: String, CodingKey {
            case forAccount
            case useCount
        }
    }

    public class ServerCreateInviteCode_Output: Codable {
        public var code: String

        public init(code: String) {
            self.code = code
        }

        enum CodingKeys: String, CodingKey {
            case code
        }
    }

    public enum ServerCreateInviteCode_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func ServerCreateInviteCode(client: any XRPCClientProtocol, input: ServerCreateInviteCode_Input) async throws -> ServerCreateInviteCode_Output {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "com.atproto.server.createInviteCode", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw ServerCreateInviteCode_Error(error: error)
        }
    }
}
