//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public enum AdminGetAccountInfo_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func AdminGetAccountInfo(client: any XRPCClientProtocol, did: String) async throws -> AdminDefs_AccountView {
        let params: Parameters = ["did": .string(did)]
        do {
            return try await client.fetch(endpoint: "com.atproto.admin.getAccountInfo", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw AdminGetAccountInfo_Error(error: error)
        }
    }
}
