//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class RepoUploadBlob_Output: Codable {
        public var blob: LexBlob

        public init(blob: LexBlob) {
            self.blob = blob
        }

        enum CodingKeys: String, CodingKey {
            case blob
        }
    }

    public enum RepoUploadBlob_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func RepoUploadBlob(client: any XRPCClientProtocol, input: Data) async throws -> RepoUploadBlob_Output {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "com.atproto.repo.uploadBlob", contentType: "*/*", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw RepoUploadBlob_Error(error: error)
        }
    }
}
