//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class LabelQueryLabels_Output: Codable {
        public var cursor: String?
        public var labels: [LabelDefs_Label]

        public init(cursor: String?, labels: [LabelDefs_Label]) {
            self.cursor = cursor
            self.labels = labels
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case labels
        }
    }

    public enum LabelQueryLabels_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func LabelQueryLabels(client: any XRPCClientProtocol, cursor: String?, limit: Int?, sources: [String]?, uriPatterns: [String]) async throws -> LabelQueryLabels_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit), "sources": .array(sources), "uriPatterns": .array(uriPatterns)]
        do {
            return try await client.fetch(endpoint: "com.atproto.label.queryLabels", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw LabelQueryLabels_Error(error: error)
        }
    }
}
