//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    public class AdminDefs_AccountView: Codable {
        public var deactivatedAt: String?
        public var did: String
        public var email: String?
        public var emailConfirmedAt: String?
        public var handle: String
        public var indexedAt: String
        public var inviteNote: String?
        public var invitedBy: ServerDefs_InviteCode?
        public var invites: [ServerDefs_InviteCode]?
        public var invitesDisabled: Bool?
        public var relatedRecords: [LexiconTypeDecoder]?

        public init(deactivatedAt: String?, did: String, email: String?, emailConfirmedAt: String?, handle: String, indexedAt: String, inviteNote: String?, invitedBy: ServerDefs_InviteCode?, invites: [ServerDefs_InviteCode]?, invitesDisabled: Bool?, relatedRecords: [LexiconTypeDecoder]?) {
            self.deactivatedAt = deactivatedAt
            self.did = did
            self.email = email
            self.emailConfirmedAt = emailConfirmedAt
            self.handle = handle
            self.indexedAt = indexedAt
            self.inviteNote = inviteNote
            self.invitedBy = invitedBy
            self.invites = invites
            self.invitesDisabled = invitesDisabled
            self.relatedRecords = relatedRecords
        }

        enum CodingKeys: String, CodingKey {
            case deactivatedAt
            case did
            case email
            case emailConfirmedAt
            case handle
            case indexedAt
            case inviteNote
            case invitedBy
            case invites
            case invitesDisabled
            case relatedRecords
        }
    }

    public class AdminDefs_RepoBlobRef: Codable {
        public var cid: String
        public var did: String
        public var recordUri: String?

        public init(cid: String, did: String, recordUri: String?) {
            self.cid = cid
            self.did = did
            self.recordUri = recordUri
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case did
            case recordUri
        }
    }

    public class AdminDefs_RepoRef: Codable {
        public var did: String

        public init(did: String) {
            self.did = did
        }

        enum CodingKeys: String, CodingKey {
            case did
        }
    }

    public class AdminDefs_StatusAttr: Codable {
        public var applied: Bool
        public var ref: String?

        public init(applied: Bool, ref: String?) {
            self.applied = applied
            self.ref = ref
        }

        enum CodingKeys: String, CodingKey {
            case applied
            case ref
        }
    }
}
