//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class EmbedExternal: Codable {
        public var external: EmbedExternal_External

        public init(external: EmbedExternal_External) {
            self.external = external
        }

        enum CodingKeys: String, CodingKey {
            case external
        }
    }

    public class EmbedExternal_External: Codable {
        public var description: String
        public var thumb: LexBlob?
        public var title: String
        public var uri: String

        public init(description: String, thumb: LexBlob?, title: String, uri: String) {
            self.description = description
            self.thumb = thumb
            self.title = title
            self.uri = uri
        }

        enum CodingKeys: String, CodingKey {
            case description
            case thumb
            case title
            case uri
        }
    }

    public class EmbedExternal_View: Codable {
        public var external: EmbedExternal_ViewExternal

        public init(external: EmbedExternal_ViewExternal) {
            self.external = external
        }

        enum CodingKeys: String, CodingKey {
            case external
        }
    }

    public class EmbedExternal_ViewExternal: Codable {
        public var description: String
        public var thumb: String?
        public var title: String
        public var uri: String

        public init(description: String, thumb: String?, title: String, uri: String) {
            self.description = description
            self.thumb = thumb
            self.title = title
            self.uri = uri
        }

        enum CodingKeys: String, CodingKey {
            case description
            case thumb
            case title
            case uri
        }
    }
}
