//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class FeedSendInteractions_Input: Codable {
        public var interactions: [FeedDefs_Interaction]

        public init(interactions: [FeedDefs_Interaction]) {
            self.interactions = interactions
        }

        enum CodingKeys: String, CodingKey {
            case interactions
        }
    }

    public class FeedSendInteractions_Output: Codable {
        public let type = "app.bsky.feed.sendInteractions"

        public init() {
        }

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }
    }

    public enum FeedSendInteractions_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func FeedSendInteractions(client: any XRPCClientProtocol, input: FeedSendInteractions_Input) async throws -> FeedSendInteractions_Output {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "app.bsky.feed.sendInteractions", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw FeedSendInteractions_Error(error: error)
        }
    }
}
