//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class GraphGetStarterPacks_Output: Codable {
        public var starterPacks: [GraphDefs_StarterPackViewBasic]

        public init(starterPacks: [GraphDefs_StarterPackViewBasic]) {
            self.starterPacks = starterPacks
        }

        enum CodingKeys: String, CodingKey {
            case starterPacks
        }
    }

    public enum GraphGetStarterPacks_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func GraphGetStarterPacks(client: any XRPCClientProtocol, uris: [String]) async throws -> GraphGetStarterPacks_Output {
        let params: Parameters = ["uris": .array(uris)]
        do {
            return try await client.fetch(endpoint: "app.bsky.graph.getStarterPacks", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw GraphGetStarterPacks_Error(error: error)
        }
    }
}
