//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class FeedGetActorFeeds_Output: Codable {
        public var cursor: String?
        public var feeds: [FeedDefs_GeneratorView]

        public init(cursor: String?, feeds: [FeedDefs_GeneratorView]) {
            self.cursor = cursor
            self.feeds = feeds
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case feeds
        }
    }

    public enum FeedGetActorFeeds_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func FeedGetActorFeeds(client: any XRPCClientProtocol, actor: String, cursor: String?, limit: Int?) async throws -> FeedGetActorFeeds_Output {
        let params: Parameters = ["actor": .string(actor), "cursor": .string(cursor), "limit": .integer(limit)]
        do {
            return try await client.fetch(endpoint: "app.bsky.feed.getActorFeeds", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw FeedGetActorFeeds_Error(error: error)
        }
    }
}
