//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class GraphUnmuteActor_Input: Codable {
        public var actor: String

        public init(actor: String) {
            self.actor = actor
        }

        enum CodingKeys: String, CodingKey {
            case actor
        }
    }

    public enum GraphUnmuteActor_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func GraphUnmuteActor(client: any XRPCClientProtocol, input: GraphUnmuteActor_Input) async throws -> Bool {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "app.bsky.graph.unmuteActor", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw GraphUnmuteActor_Error(error: error)
        }
    }
}
