//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class GraphGetListBlocks_Output: Codable {
        public var cursor: String?
        public var lists: [GraphDefs_ListView]

        public init(cursor: String?, lists: [GraphDefs_ListView]) {
            self.cursor = cursor
            self.lists = lists
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case lists
        }
    }

    public enum GraphGetListBlocks_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func GraphGetListBlocks(client: any XRPCClientProtocol, cursor: String?, limit: Int?) async throws -> GraphGetListBlocks_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit)]
        do {
            return try await client.fetch(endpoint: "app.bsky.graph.getListBlocks", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw GraphGetListBlocks_Error(error: error)
        }
    }
}
