//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class GraphStarterpack_FeedItem: Codable {
        public var uri: String

        public init(uri: String) {
            self.uri = uri
        }

        enum CodingKeys: String, CodingKey {
            case uri
        }
    }
}

public class appbskytypes_GraphStarterpack: Codable {
    public let type = "app.bsky.graph.starterpack"
    public var createdAt: String
    public var description: String?
    public var descriptionFacets: [appbskytypes.RichtextFacet]?
    public var feeds: [appbskytypes.GraphStarterpack_FeedItem]?
    public var list: String
    public var name: String

    public init(createdAt: String, description: String?, descriptionFacets: [appbskytypes.RichtextFacet]?, feeds: [appbskytypes.GraphStarterpack_FeedItem]?, list: String, name: String) {
        self.createdAt = createdAt
        self.description = description
        self.descriptionFacets = descriptionFacets
        self.feeds = feeds
        self.list = list
        self.name = name
    }

    enum CodingKeys: String, CodingKey {
        case type = "$type"
        case createdAt
        case description
        case descriptionFacets
        case feeds
        case list
        case name
    }
}
