//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class ActorPutPreferences_Input: Codable {
        public var preferences: [ActorDefs_Preferences_Elem]

        public init(preferences: [ActorDefs_Preferences_Elem]) {
            self.preferences = preferences
        }

        enum CodingKeys: String, CodingKey {
            case preferences
        }
    }

    public enum ActorPutPreferences_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func ActorPutPreferences(client: any XRPCClientProtocol, input: ActorPutPreferences_Input) async throws -> Bool {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "app.bsky.actor.putPreferences", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw ActorPutPreferences_Error(error: error)
        }
    }
}
