//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class LabelerGetServices_Output: Codable {
        public var views: [LabelerGetServices_Output_Views_Elem]

        public init(views: [LabelerGetServices_Output_Views_Elem]) {
            self.views = views
        }

        enum CodingKeys: String, CodingKey {
            case views
        }
    }

    public enum LabelerGetServices_Output_Views_Elem: Codable {
        case labelerDefsLabelerView(LabelerDefs_LabelerView)
        case labelerDefsLabelerViewDetailed(LabelerDefs_LabelerViewDetailed)
        case unknown(UnknownRecord)

        enum CodingKeys: String, CodingKey {
            case type = "$type"
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let type = try container.decode(String.self, forKey: .type)
            switch type {
            case "app.bsky.labeler.defs#labelerView":
                self = try .labelerDefsLabelerView(.init(from: decoder))
            case "app.bsky.labeler.defs#labelerViewDetailed":
                self = try .labelerDefsLabelerViewDetailed(.init(from: decoder))
            default:
                self = try .unknown(.init(from: decoder))
            }
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            switch self {
            case let .labelerDefsLabelerView(value):
                try container.encode("app.bsky.labeler.defs#labelerView", forKey: .type)
                try value.encode(to: encoder)
            case let .labelerDefsLabelerViewDetailed(value):
                try container.encode("app.bsky.labeler.defs#labelerViewDetailed", forKey: .type)
                try value.encode(to: encoder)
            case .unknown:
                break
            }
        }
    }

    public enum LabelerGetServices_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func LabelerGetServices(client: any XRPCClientProtocol, detailed: Bool?, dids: [String]) async throws -> LabelerGetServices_Output {
        let params: Parameters = ["detailed": .bool(detailed), "dids": .array(dids)]
        do {
            return try await client.fetch(endpoint: "app.bsky.labeler.getServices", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw LabelerGetServices_Error(error: error)
        }
    }
}
