//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class NotificationUpdateSeen_Input: Codable {
        public var seenAt: String

        public init(seenAt: String) {
            self.seenAt = seenAt
        }

        enum CodingKeys: String, CodingKey {
            case seenAt
        }
    }

    public enum NotificationUpdateSeen_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func NotificationUpdateSeen(client: any XRPCClientProtocol, input: NotificationUpdateSeen_Input) async throws -> Bool {
        let params: Bool? = nil
        do {
            return try await client.fetch(endpoint: "app.bsky.notification.updateSeen", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
        } catch let error as UnExpectedError {
            throw NotificationUpdateSeen_Error(error: error)
        }
    }
}
