//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class ActorGetProfiles_Output: Codable {
        public var profiles: [ActorDefs_ProfileViewDetailed]

        public init(profiles: [ActorDefs_ProfileViewDetailed]) {
            self.profiles = profiles
        }

        enum CodingKeys: String, CodingKey {
            case profiles
        }
    }

    public enum ActorGetProfiles_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func ActorGetProfiles(client: any XRPCClientProtocol, actors: [String]) async throws -> ActorGetProfiles_Output {
        let params: Parameters = ["actors": .array(actors)]
        do {
            return try await client.fetch(endpoint: "app.bsky.actor.getProfiles", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw ActorGetProfiles_Error(error: error)
        }
    }
}
