//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class EmbedImages: Codable {
        public var images: [EmbedImages_Image]

        public init(images: [EmbedImages_Image]) {
            self.images = images
        }

        enum CodingKeys: String, CodingKey {
            case images
        }
    }

    public class EmbedImages_AspectRatio: Codable {
        public var height: Int
        public var width: Int

        public init(height: Int, width: Int) {
            self.height = height
            self.width = width
        }

        enum CodingKeys: String, CodingKey {
            case height
            case width
        }
    }

    public class EmbedImages_Image: Codable {
        public var alt: String
        public var aspectRatio: EmbedImages_AspectRatio?
        public var image: LexBlob

        public init(alt: String, aspectRatio: EmbedImages_AspectRatio?, image: LexBlob) {
            self.alt = alt
            self.aspectRatio = aspectRatio
            self.image = image
        }

        enum CodingKeys: String, CodingKey {
            case alt
            case aspectRatio
            case image
        }
    }

    public class EmbedImages_View: Codable {
        public var images: [EmbedImages_ViewImage]

        public init(images: [EmbedImages_ViewImage]) {
            self.images = images
        }

        enum CodingKeys: String, CodingKey {
            case images
        }
    }

    public class EmbedImages_ViewImage: Codable {
        public var alt: String
        public var aspectRatio: EmbedImages_AspectRatio?
        public var fullsize: String
        public var thumb: String

        public init(alt: String, aspectRatio: EmbedImages_AspectRatio?, fullsize: String, thumb: String) {
            self.alt = alt
            self.aspectRatio = aspectRatio
            self.fullsize = fullsize
            self.thumb = thumb
        }

        enum CodingKeys: String, CodingKey {
            case alt
            case aspectRatio
            case fullsize
            case thumb
        }
    }
}
