//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class GraphGetSuggestedFollowsByActor_Output: Codable {
        public var suggestions: [ActorDefs_ProfileView]

        public init(suggestions: [ActorDefs_ProfileView]) {
            self.suggestions = suggestions
        }

        enum CodingKeys: String, CodingKey {
            case suggestions
        }
    }

    public enum GraphGetSuggestedFollowsByActor_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func GraphGetSuggestedFollowsByActor(client: any XRPCClientProtocol, actor: String) async throws -> GraphGetSuggestedFollowsByActor_Output {
        let params: Parameters = ["actor": .string(actor)]
        do {
            return try await client.fetch(endpoint: "app.bsky.graph.getSuggestedFollowsByActor", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw GraphGetSuggestedFollowsByActor_Error(error: error)
        }
    }
}
