//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class UnspeccedGetSuggestionsSkeleton_Output: Codable {
        public var actors: [UnspeccedDefs_SkeletonSearchActor]
        public var cursor: String?

        public init(actors: [UnspeccedDefs_SkeletonSearchActor], cursor: String?) {
            self.actors = actors
            self.cursor = cursor
        }

        enum CodingKeys: String, CodingKey {
            case actors
            case cursor
        }
    }

    public enum UnspeccedGetSuggestionsSkeleton_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func UnspeccedGetSuggestionsSkeleton(client: any XRPCClientProtocol, cursor: String?, limit: Int?, relativeToDid: String?, viewer: String?) async throws -> UnspeccedGetSuggestionsSkeleton_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit), "relativeToDid": .string(relativeToDid), "viewer": .string(viewer)]
        do {
            return try await client.fetch(endpoint: "app.bsky.unspecced.getSuggestionsSkeleton", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw UnspeccedGetSuggestionsSkeleton_Error(error: error)
        }
    }
}
