//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class ActorSearchActors_Output: Codable {
        public var actors: [ActorDefs_ProfileView]
        public var cursor: String?

        public init(actors: [ActorDefs_ProfileView], cursor: String?) {
            self.actors = actors
            self.cursor = cursor
        }

        enum CodingKeys: String, CodingKey {
            case actors
            case cursor
        }
    }

    public enum ActorSearchActors_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func ActorSearchActors(client: any XRPCClientProtocol, cursor: String?, limit: Int?, q: String?, term: String?) async throws -> ActorSearchActors_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit), "q": .string(q), "term": .string(term)]
        do {
            return try await client.fetch(endpoint: "app.bsky.actor.searchActors", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw ActorSearchActors_Error(error: error)
        }
    }
}
