//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class GraphGetList_Output: Codable {
        public var cursor: String?
        public var items: [GraphDefs_ListItemView]
        public var list: GraphDefs_ListView

        public init(cursor: String?, items: [GraphDefs_ListItemView], list: GraphDefs_ListView) {
            self.cursor = cursor
            self.items = items
            self.list = list
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case items
            case list
        }
    }

    public enum GraphGetList_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func GraphGetList(client: any XRPCClientProtocol, cursor: String?, limit: Int?, list: String) async throws -> GraphGetList_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit), "list": .string(list)]
        do {
            return try await client.fetch(endpoint: "app.bsky.graph.getList", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw GraphGetList_Error(error: error)
        }
    }
}
