//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class FeedGetListFeed_Output: Codable {
        public var cursor: String?
        public var feed: [FeedDefs_FeedViewPost]

        public init(cursor: String?, feed: [FeedDefs_FeedViewPost]) {
            self.cursor = cursor
            self.feed = feed
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case feed
        }
    }

    public enum FeedGetListFeed_Error: XRPCError {
        case unknownlist(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "UnknownList":
                self = .unknownlist(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .unknownlist:
                return "UnknownList"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unknownlist(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func FeedGetListFeed(client: any XRPCClientProtocol, cursor: String?, limit: Int?, list: String) async throws -> FeedGetListFeed_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit), "list": .string(list)]
        do {
            return try await client.fetch(endpoint: "app.bsky.feed.getListFeed", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw FeedGetListFeed_Error(error: error)
        }
    }
}
