//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class GraphDefs_ListItemView: Codable {
        public var subject: ActorDefs_ProfileView
        public var uri: String

        public init(subject: ActorDefs_ProfileView, uri: String) {
            self.subject = subject
            self.uri = uri
        }

        enum CodingKeys: String, CodingKey {
            case subject
            case uri
        }
    }

    public enum GraphDefs_ListPurpose: RawRepresentable, Codable {
        public typealias RawValue = String

        case appBskyGraphDefsModlist
        case appBskyGraphDefsCuratelist
        case appBskyGraphDefsReferencelist
        case unknown(String)

        public init?(rawValue: String) {
            switch rawValue {
            case "app.bsky.graph.defs#modlist":
                self = .appBskyGraphDefsModlist
            case "app.bsky.graph.defs#curatelist":
                self = .appBskyGraphDefsCuratelist
            case "app.bsky.graph.defs#referencelist":
                self = .appBskyGraphDefsReferencelist
            default:
                self = .unknown(rawValue)
            }
        }

        public var rawValue: String {
            switch self {
            case .appBskyGraphDefsModlist:
                "app.bsky.graph.defs#modlist"
            case .appBskyGraphDefsCuratelist:
                "app.bsky.graph.defs#curatelist"
            case .appBskyGraphDefsReferencelist:
                "app.bsky.graph.defs#referencelist"
            case let .unknown(value):
                value
            }
        }

        public init(from decoder: any Decoder) throws {
            let rawValue = try String(from: decoder)
            self = Self (rawValue: rawValue)!
        }

        public func encode(to encoder: any Encoder) throws {
            try rawValue.encode(to: encoder)
        }
    }

    public class GraphDefs_ListView: Codable {
        public var avatar: String?
        public var cid: String
        public var creator: ActorDefs_ProfileView
        public var description: String?
        public var descriptionFacets: [RichtextFacet]?
        public var indexedAt: String
        public var labels: [comatprototypes.LabelDefs_Label]?
        public var listItemCount: Int?
        public var name: String
        public var purpose: GraphDefs_ListPurpose
        public var uri: String
        public var viewer: GraphDefs_ListViewerState?

        public init(avatar: String?, cid: String, creator: ActorDefs_ProfileView, description: String?, descriptionFacets: [RichtextFacet]?, indexedAt: String, labels: [comatprototypes.LabelDefs_Label]?, listItemCount: Int?, name: String, purpose: GraphDefs_ListPurpose, uri: String, viewer: GraphDefs_ListViewerState?) {
            self.avatar = avatar
            self.cid = cid
            self.creator = creator
            self.description = description
            self.descriptionFacets = descriptionFacets
            self.indexedAt = indexedAt
            self.labels = labels
            self.listItemCount = listItemCount
            self.name = name
            self.purpose = purpose
            self.uri = uri
            self.viewer = viewer
        }

        enum CodingKeys: String, CodingKey {
            case avatar
            case cid
            case creator
            case description
            case descriptionFacets
            case indexedAt
            case labels
            case listItemCount
            case name
            case purpose
            case uri
            case viewer
        }
    }

    public class GraphDefs_ListViewBasic: Codable {
        public var avatar: String?
        public var cid: String
        public var indexedAt: String?
        public var labels: [comatprototypes.LabelDefs_Label]?
        public var listItemCount: Int?
        public var name: String
        public var purpose: GraphDefs_ListPurpose
        public var uri: String
        public var viewer: GraphDefs_ListViewerState?

        public init(avatar: String?, cid: String, indexedAt: String?, labels: [comatprototypes.LabelDefs_Label]?, listItemCount: Int?, name: String, purpose: GraphDefs_ListPurpose, uri: String, viewer: GraphDefs_ListViewerState?) {
            self.avatar = avatar
            self.cid = cid
            self.indexedAt = indexedAt
            self.labels = labels
            self.listItemCount = listItemCount
            self.name = name
            self.purpose = purpose
            self.uri = uri
            self.viewer = viewer
        }

        enum CodingKeys: String, CodingKey {
            case avatar
            case cid
            case indexedAt
            case labels
            case listItemCount
            case name
            case purpose
            case uri
            case viewer
        }
    }

    public class GraphDefs_ListViewerState: Codable {
        public var blocked: String?
        public var muted: Bool?

        public init(blocked: String?, muted: Bool?) {
            self.blocked = blocked
            self.muted = muted
        }

        enum CodingKeys: String, CodingKey {
            case blocked
            case muted
        }
    }

    public class GraphDefs_NotFoundActor: Codable {
        public var actor: String
        public var notFound: Bool

        public init(actor: String, notFound: Bool) {
            self.actor = actor
            self.notFound = notFound
        }

        enum CodingKeys: String, CodingKey {
            case actor
            case notFound
        }
    }

    public class GraphDefs_Relationship: Codable {
        public var did: String
        public var followedBy: String?
        public var following: String?

        public init(did: String, followedBy: String?, following: String?) {
            self.did = did
            self.followedBy = followedBy
            self.following = following
        }

        enum CodingKeys: String, CodingKey {
            case did
            case followedBy
            case following
        }
    }

    public class GraphDefs_StarterPackView: Codable {
        public var cid: String
        public var creator: ActorDefs_ProfileViewBasic
        public var feeds: [FeedDefs_GeneratorView]?
        public var indexedAt: String
        public var joinedAllTimeCount: Int?
        public var joinedWeekCount: Int?
        public var labels: [comatprototypes.LabelDefs_Label]?
        public var list: GraphDefs_ListViewBasic?
        public var listItemsSample: [GraphDefs_ListItemView]?
        public var record: LexiconTypeDecoder
        public var uri: String

        public init(cid: String, creator: ActorDefs_ProfileViewBasic, feeds: [FeedDefs_GeneratorView]?, indexedAt: String, joinedAllTimeCount: Int?, joinedWeekCount: Int?, labels: [comatprototypes.LabelDefs_Label]?, list: GraphDefs_ListViewBasic?, listItemsSample: [GraphDefs_ListItemView]?, record: LexiconTypeDecoder, uri: String) {
            self.cid = cid
            self.creator = creator
            self.feeds = feeds
            self.indexedAt = indexedAt
            self.joinedAllTimeCount = joinedAllTimeCount
            self.joinedWeekCount = joinedWeekCount
            self.labels = labels
            self.list = list
            self.listItemsSample = listItemsSample
            self.record = record
            self.uri = uri
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case creator
            case feeds
            case indexedAt
            case joinedAllTimeCount
            case joinedWeekCount
            case labels
            case list
            case listItemsSample
            case record
            case uri
        }
    }

    public class GraphDefs_StarterPackViewBasic: Codable {
        public var cid: String
        public var creator: ActorDefs_ProfileViewBasic
        public var indexedAt: String
        public var joinedAllTimeCount: Int?
        public var joinedWeekCount: Int?
        public var labels: [comatprototypes.LabelDefs_Label]?
        public var listItemCount: Int?
        public var record: LexiconTypeDecoder
        public var uri: String

        public init(cid: String, creator: ActorDefs_ProfileViewBasic, indexedAt: String, joinedAllTimeCount: Int?, joinedWeekCount: Int?, labels: [comatprototypes.LabelDefs_Label]?, listItemCount: Int?, record: LexiconTypeDecoder, uri: String) {
            self.cid = cid
            self.creator = creator
            self.indexedAt = indexedAt
            self.joinedAllTimeCount = joinedAllTimeCount
            self.joinedWeekCount = joinedWeekCount
            self.labels = labels
            self.listItemCount = listItemCount
            self.record = record
            self.uri = uri
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case creator
            case indexedAt
            case joinedAllTimeCount
            case joinedWeekCount
            case labels
            case listItemCount
            case record
            case uri
        }
    }
}
