//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class FeedGetActorLikes_Output: Codable {
        public var cursor: String?
        public var feed: [FeedDefs_FeedViewPost]

        public init(cursor: String?, feed: [FeedDefs_FeedViewPost]) {
            self.cursor = cursor
            self.feed = feed
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case feed
        }
    }

    public enum FeedGetActorLikes_Error: XRPCError {
        case blockedactor(String?)
        case blockedbyactor(String?)
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            case "BlockedActor":
                self = .blockedactor(error.message)
            case "BlockedByActor":
                self = .blockedbyactor(error.message)
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case .blockedactor:
                return "BlockedActor"
            case .blockedbyactor:
                return "BlockedByActor"
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .blockedactor(message):
                return message
            case let .blockedbyactor(message):
                return message
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func FeedGetActorLikes(client: any XRPCClientProtocol, actor: String, cursor: String?, limit: Int?) async throws -> FeedGetActorLikes_Output {
        let params: Parameters = ["actor": .string(actor), "cursor": .string(cursor), "limit": .integer(limit)]
        do {
            return try await client.fetch(endpoint: "app.bsky.feed.getActorLikes", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw FeedGetActorLikes_Error(error: error)
        }
    }
}
