//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class ActorSearchActorsTypeahead_Output: Codable {
        public var actors: [ActorDefs_ProfileViewBasic]

        public init(actors: [ActorDefs_ProfileViewBasic]) {
            self.actors = actors
        }

        enum CodingKeys: String, CodingKey {
            case actors
        }
    }

    public enum ActorSearchActorsTypeahead_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func ActorSearchActorsTypeahead(client: any XRPCClientProtocol, limit: Int?, q: String?, term: String?) async throws -> ActorSearchActorsTypeahead_Output {
        let params: Parameters = ["limit": .integer(limit), "q": .string(q), "term": .string(term)]
        do {
            return try await client.fetch(endpoint: "app.bsky.actor.searchActorsTypeahead", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw ActorSearchActorsTypeahead_Error(error: error)
        }
    }
}
