//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class GraphGetMutes_Output: Codable {
        public var cursor: String?
        public var mutes: [ActorDefs_ProfileView]

        public init(cursor: String?, mutes: [ActorDefs_ProfileView]) {
            self.cursor = cursor
            self.mutes = mutes
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case mutes
        }
    }

    public enum GraphGetMutes_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func GraphGetMutes(client: any XRPCClientProtocol, cursor: String?, limit: Int?) async throws -> GraphGetMutes_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit)]
        do {
            return try await client.fetch(endpoint: "app.bsky.graph.getMutes", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw GraphGetMutes_Error(error: error)
        }
    }
}
