//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class FeedGetFeedGenerator_Output: Codable {
        public var isOnline: Bool
        public var isValid: Bool
        public var view: FeedDefs_GeneratorView

        public init(isOnline: Bool, isValid: Bool, view: FeedDefs_GeneratorView) {
            self.isOnline = isOnline
            self.isValid = isValid
            self.view = view
        }

        enum CodingKeys: String, CodingKey {
            case isOnline
            case isValid
            case view
        }
    }

    public enum FeedGetFeedGenerator_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func FeedGetFeedGenerator(client: any XRPCClientProtocol, feed: String) async throws -> FeedGetFeedGenerator_Output {
        let params: Parameters = ["feed": .string(feed)]
        do {
            return try await client.fetch(endpoint: "app.bsky.feed.getFeedGenerator", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw FeedGetFeedGenerator_Error(error: error)
        }
    }
}
