//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class FeedGetRepostedBy_Output: Codable {
        public var cid: String?
        public var cursor: String?
        public var repostedBy: [ActorDefs_ProfileView]
        public var uri: String

        public init(cid: String?, cursor: String?, repostedBy: [ActorDefs_ProfileView], uri: String) {
            self.cid = cid
            self.cursor = cursor
            self.repostedBy = repostedBy
            self.uri = uri
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case cursor
            case repostedBy
            case uri
        }
    }

    public enum FeedGetRepostedBy_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func FeedGetRepostedBy(client: any XRPCClientProtocol, cid: String?, cursor: String?, limit: Int?, uri: String) async throws -> FeedGetRepostedBy_Output {
        let params: Parameters = ["cid": .string(cid), "cursor": .string(cursor), "limit": .integer(limit), "uri": .string(uri)]
        do {
            return try await client.fetch(endpoint: "app.bsky.feed.getRepostedBy", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw FeedGetRepostedBy_Error(error: error)
        }
    }
}
