//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class GraphGetStarterPack_Output: Codable {
        public var starterPack: GraphDefs_StarterPackView

        public init(starterPack: GraphDefs_StarterPackView) {
            self.starterPack = starterPack
        }

        enum CodingKeys: String, CodingKey {
            case starterPack
        }
    }

    public enum GraphGetStarterPack_Error: XRPCError {
        case unexpected(error: String?, message: String?)

        public init(error: UnExpectedError) {
            switch error.error {
            default:
                self = .unexpected(error: error.error, message: error.message)
            }
        }

        public var error: String? {
            switch self {
            case let .unexpected(error, _):
                return error
            }
        }

        public var message: String? {
            switch self {
            case let .unexpected(_, message):
                return message
            }
        }
    }

    public static func GraphGetStarterPack(client: any XRPCClientProtocol, starterPack: String) async throws -> GraphGetStarterPack_Output {
        let params: Parameters = ["starterPack": .string(starterPack)]
        do {
            return try await client.fetch(endpoint: "app.bsky.graph.getStarterPack", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
        } catch let error as UnExpectedError {
            throw GraphGetStarterPack_Error(error: error)
        }
    }
}
