//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    public class LabelerDefs_LabelerPolicies: Codable {
        public var labelValueDefinitions: [comatprototypes.LabelDefs_LabelValueDefinition]?
        public var labelValues: [comatprototypes.LabelDefs_LabelValue]

        public init(labelValueDefinitions: [comatprototypes.LabelDefs_LabelValueDefinition]?, labelValues: [comatprototypes.LabelDefs_LabelValue]) {
            self.labelValueDefinitions = labelValueDefinitions
            self.labelValues = labelValues
        }

        enum CodingKeys: String, CodingKey {
            case labelValueDefinitions
            case labelValues
        }
    }

    public class LabelerDefs_LabelerView: Codable {
        public var cid: String
        public var creator: ActorDefs_ProfileView
        public var indexedAt: String
        public var labels: [comatprototypes.LabelDefs_Label]?
        public var likeCount: Int?
        public var uri: String
        public var viewer: LabelerDefs_LabelerViewerState?

        public init(cid: String, creator: ActorDefs_ProfileView, indexedAt: String, labels: [comatprototypes.LabelDefs_Label]?, likeCount: Int?, uri: String, viewer: LabelerDefs_LabelerViewerState?) {
            self.cid = cid
            self.creator = creator
            self.indexedAt = indexedAt
            self.labels = labels
            self.likeCount = likeCount
            self.uri = uri
            self.viewer = viewer
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case creator
            case indexedAt
            case labels
            case likeCount
            case uri
            case viewer
        }
    }

    public class LabelerDefs_LabelerViewDetailed: Codable {
        public var cid: String
        public var creator: ActorDefs_ProfileView
        public var indexedAt: String
        public var labels: [comatprototypes.LabelDefs_Label]?
        public var likeCount: Int?
        public var policies: LabelerDefs_LabelerPolicies
        public var uri: String
        public var viewer: LabelerDefs_LabelerViewerState?

        public init(cid: String, creator: ActorDefs_ProfileView, indexedAt: String, labels: [comatprototypes.LabelDefs_Label]?, likeCount: Int?, policies: LabelerDefs_LabelerPolicies, uri: String, viewer: LabelerDefs_LabelerViewerState?) {
            self.cid = cid
            self.creator = creator
            self.indexedAt = indexedAt
            self.labels = labels
            self.likeCount = likeCount
            self.policies = policies
            self.uri = uri
            self.viewer = viewer
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case creator
            case indexedAt
            case labels
            case likeCount
            case policies
            case uri
            case viewer
        }
    }

    public class LabelerDefs_LabelerViewerState: Codable {
        public var like: String?

        public init(like: String?) {
            self.like = like
        }

        enum CodingKeys: String, CodingKey {
            case like
        }
    }
}
