//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

public class appbskytypes_GraphFollow: Codable {
    public let type = "app.bsky.graph.follow"
    public var createdAt: String
    public var subject: String

    public init(createdAt: String, subject: String) {
        self.createdAt = createdAt
        self.subject = subject
    }

    enum CodingKeys: String, CodingKey {
        case type = "$type"
        case createdAt
        case subject
    }
}
